---
- hosts: staging
  gather_facts: no
  tasks:
    - name: Install Docker, python3-pip, openJDK and git on the staging machine
      become: true
      apt:
        pkg:
          - docker.io
          - python3-pip
          - default-jdk
          - git
        state: latest
        update_cache: true

    - name: Install docker-compose on the staging machine
      get_url:
        url:  https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64
        dest: /bin/docker-compose
        mode: 'u+x,g+x'

    - name: Install Docker Module for Python on the staging machine
      pip:
        name: docker

    - name: Git Clone repository Boxfuse on the staging machine
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello
        clone: yes
        dest: /tmp/boxfuse-sample-java-war-hello

            - name: Start docker service on the staging machine
      service:
        name: docker
        state: started
        enabled: true

    - name: create build directory on the staging machine
      file:
        path: "{{ playbook_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy configuration files Docker on the staging machine
      copy:
        src: '{{ item }}'
        dest: "{{ playbook_dir }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - Dockerfile
        - docker-compose.yml

    - name: Start container using docker-compose on the staging machine
      become: true
      shell:
        cmd: "docker-compose up -d"
      args:
        chdir: "{{ playbook_dir }}"

    - name: Remove the build directory on the staging machine
      ansible.builtin.file:
        path: "{{ playbook_dir }}"
        state: absent
