---
- name: Installation Tomcat on the Production machine
  hosts:  production
  become: yes

  tasks:
    - name: Create a workind directory on the Production machine
      file:
        path: "{{ playbook_dir }}"
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Download Tomcat a workind directory on the Production machine
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.19/bin/apache-tomcat-10.1.19.tar.gz
        dest: "{{ playbook_dir }}"

    - name: Create directory for Tomcat on the Production machine
      file:
        path: "/opt/tomcat/"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Extract archive Tomcat on the Production machine
      unarchive:
        src: "{{ playbook_dir }}/apache-tomcat-10.1.19.tar.gz"
        dest: "/opt/tomcat"
        extra_opts: [--strip-components=1]
        remote_src: yes

    - name: Remove the working directory on the Production machine
      ansible.builtin.file:
        path: "{{ playbook_dir }}"
        state: absent

    - name: start apache-tomcat on the Production machine
      command: nohup "/opt/tomcat/bin/startup.sh"

- name: Copy artefact from staging to production server
  hosts: production
  become: true
  tasks:
    - name: Transfer war-file from staging to production server
      synchronize:
        src: "/var/lib/docker/volumes/project_web_data/_data/hello-1.0.war"
        dest: "/opt/tomcat/webapps/"
      delegate_to: staging
