---
version: "3"
services:
  maven:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maven
    volumes:
      - web_data:/boxfuse/boxfuse-sample-java-war-hello/target/
volumes:
  web_data:
